name = "devpkg_R"
version = "0.1.0"
license = "license"
author = "Chitran1987"
maintainer = "ghosal.chitran@gmail.com"
copyright = "Copyright 2025, Chitran1987"

[build]
auto-executables = true
auto-tests       = true
auto-examples    = false
module-naming    = false
link             = ["fftw3f", "m", "openblas"]

[install]
library = false
test    = false

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"
